import Link from "next/link";
import { ArrowLeft, ShieldCheck } from "lucide-react";
import { LoginForm } from "@/components/admin/login-form";
import { BrandLogo } from "@/components/brand-logo";

export const metadata = { title: "Acesso administrativo" };
export default function AdminLogin() {
  return <main className="grid min-h-screen bg-[#071b2c] lg:grid-cols-2"><section className="relative hidden overflow-hidden p-14 text-white lg:flex lg:flex-col lg:justify-between"><div className="hero-grid absolute inset-0" /><div className="relative flex items-center gap-3"><BrandLogo className="size-14 border border-white/20" /><strong className="display-font tracking-[.09em]">AEROMÉDICO BRASIL</strong></div><div className="relative max-w-lg"><span className="text-xs font-bold uppercase tracking-[.24em] text-[#ef9a9d]">Controle central</span><h1 className="display-font mt-5 text-6xl font-black uppercase leading-[.9]">Conteúdo, leads e vendas em uma só visão.</h1><p className="mt-6 leading-7 text-slate-300">Gerencie a experiência pública sem precisar alterar o código da landing page.</p></div><div className="relative flex items-center gap-2 text-xs text-slate-400"><ShieldCheck className="size-4 text-[#ef9a9d]" /> Autenticação Supabase e proteção por políticas RLS.</div></section><section className="grid place-items-center bg-[#f9f7f7] px-5 py-12"><div className="w-full max-w-md"><Link href="/" className="mb-8 inline-flex items-center gap-2 text-sm font-medium text-slate-500 hover:text-[#071b2c]"><ArrowLeft className="size-4" /> Voltar para o site</Link><div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-[0_28px_80px_rgba(7,24,43,.1)] sm:p-9"><span className="grid size-12 place-items-center rounded-2xl bg-[#c9060a] text-white"><ShieldCheck /></span><h2 className="mt-6 text-3xl font-black text-[#071b2c]">Acesso do administrador</h2><p className="mt-2 text-sm leading-6 text-slate-500">Entre com as credenciais autorizadas para gerenciar a plataforma.</p><LoginForm /></div></div></section></main>;
}
