"use client";
import { Activity, ArrowUpRight, BookOpen, DollarSign, MousePointerClick, Users } from "lucide-react";
import { StatCard } from "./stat-card";

const bars = [38, 52, 46, 68, 58, 76, 64, 88, 72, 82, 93, 78];
export function DashboardOverview() {
  return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Leads capturados" value="1.284" change="+18,2%" icon={Users} /><StatCard label="Cliques nos cursos" value="3.760" change="+11,4%" icon={MousePointerClick} accent="cyan" /><StatCard label="Materiais baixados" value="892" change="+24,1%" icon={BookOpen} accent="orange" /><StatCard label="Faturamento" value="R$ 28.450" change="+9,8%" icon={DollarSign} accent="green" /></div>
  <div className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_.8fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold">Evolução dos leads</h2><p className="mt-1 text-xs text-slate-400">Últimos 12 meses</p></div><span className="rounded-xl border border-slate-200 px-3 py-2 text-xs">2026</span></div><div className="mt-8 flex h-56 items-end gap-2 rounded-xl bg-gradient-to-b from-blue-50/60 to-transparent p-4 sm:gap-4">{bars.map((height, index) => <div key={index} className="group relative flex h-full flex-1 items-end"><div className="w-full rounded-t-md bg-gradient-to-t from-[#1175d1] to-[#38c5ea] opacity-85 transition group-hover:opacity-100" style={{ height: `${height}%` }} /><span className="absolute -bottom-7 left-1/2 -translate-x-1/2 text-[9px] text-slate-400">{index + 1}</span></div>)}</div><div className="mt-10 flex items-center gap-2 text-xs font-semibold text-emerald-600"><ArrowUpRight className="size-4" /> 18,2% acima do período anterior</div></section>
  <section className="rounded-2xl border border-slate-200 bg-[#07182b] p-6 text-white shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold">Conversão do funil</h2><p className="mt-1 text-xs text-slate-400">Visão consolidada</p></div><Activity className="size-5 text-[#38c5ea]" /></div><div className="mt-8 space-y-6">{[["Visitantes","12.480",100],["Leads","1.284",70],["Checkout","416",43],["Vendas","96",23]].map(([label,value,width]) => <div key={label as string}><div className="mb-2 flex justify-between text-xs"><span className="text-slate-400">{label as string}</span><strong>{value as string}</strong></div><div className="h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-[#1175d1] to-[#38c5ea]" style={{ width: `${width}%` }} /></div></div>)}</div><p className="mt-8 rounded-xl bg-white/5 p-4 text-xs leading-5 text-slate-400">Dados demonstrativos. Ao conectar o Supabase e o gateway, os indicadores passam a refletir eventos reais.</p></section></div></>;
}
