import Link from "next/link";
import { Activity, ArrowRight, BookOpen, Camera, Check, ChevronRight, CirclePlay, Clock3, FileText, GraduationCap, Mail, Map, Mic2, Plane, Route, ShieldCheck, Sparkles, Star, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { courses, materials, services } from "@/data/site";
import { formatCurrency, cn } from "@/lib/utils";
import { Faq } from "./faq";
import { Header } from "./header";
import { LeadForm } from "./lead-form";
import { BrandLogo } from "@/components/brand-logo";

const serviceIcons = { plane: Plane, activity: Activity, route: Route, mic: Mic2 };

function SectionHeading({ eyebrow, title, copy, light = false }: { eyebrow: string; title: string; copy?: string; light?: boolean }) {
  return <div className="max-w-2xl"><p className={cn("mb-4 text-xs font-bold uppercase tracking-[.24em]", light ? "text-[#ef9a9d]" : "text-[#c9060a]")}>{eyebrow}</p><h2 className={cn("display-font text-4xl font-black uppercase leading-[.98] tracking-[-.03em] sm:text-5xl", light ? "text-white" : "text-[#071b2c]")}>{title}</h2>{copy && <p className={cn("mt-5 text-base leading-7", light ? "text-slate-300" : "text-slate-600")}>{copy}</p>}</div>;
}

type LandingContent = Record<string, { title: string; body: string | null }>;

export function LandingPage({ content = {} }: { content?: LandingContent }) {
  const hero = content.hero;
  const about = content.about;
  const finalCta = content["final-cta"];
  return (
    <main className="overflow-hidden">
      <Header />
      <section className="relative min-h-[760px] overflow-hidden bg-[#03111d] pt-20 text-white">
        <div className="hero-grid absolute inset-0" /><div className="noise pointer-events-none absolute inset-0 opacity-20" />
        <div className="absolute -left-32 top-40 size-96 rounded-full bg-[#28688f]/18 blur-[100px]" /><div className="absolute -right-32 top-20 size-[460px] rounded-full bg-[#c9060a]/20 blur-[120px]" />
        <div className="page-shell relative grid min-h-[680px] items-center gap-14 py-20 lg:grid-cols-[1.08fr_.92fr] lg:py-16">
          <div className="pt-8 lg:pt-0">
            <Badge><Sparkles className="size-3.5" /> Conhecimento que prepara para a missão</Badge>
            <h1 className="display-font mt-7 max-w-3xl text-5xl font-black uppercase leading-[.9] tracking-[-.045em] sm:text-7xl lg:text-[5.5rem]">{hero?.title ?? <>O mundo <span className="text-[#ef5357]">aeromédico</span> começa antes do voo.</>}</h1>
            <p className="mt-7 max-w-xl text-base leading-7 text-slate-300 sm:text-lg">{hero?.body ?? "Formação, carreira e conteúdo para profissionais que querem compreender o ambiente, antecipar riscos e elevar a assistência no transporte aeromédico e no APH."}</p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row">
              <Link href="#cursos" className={cn(buttonVariants({ size: "lg" }))}>Quero me preparar <ArrowRight className="size-4" /></Link>
              <Link href="#sobre" className={cn(buttonVariants({ variant: "secondary", size: "lg" }))}><CirclePlay className="size-5" /> Conheça o projeto</Link>
            </div>
            <div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-xs font-medium text-slate-400">
              <span className="flex items-center gap-2"><ShieldCheck className="size-4 text-[#ef5357]" /> Conteúdo técnico</span><span className="flex items-center gap-2"><GraduationCap className="size-4 text-[#ef5357]" /> Aprendizado aplicável</span><span className="flex items-center gap-2"><Users className="size-4 text-[#ef5357]" /> Comunidade ativa</span>
            </div>
          </div>
          <div className="relative mx-auto w-full max-w-[530px] py-10">
            <div className="absolute -inset-10 rounded-full bg-[#c9060a]/22 blur-[90px]" />
            <div className="glass relative mx-auto aspect-square max-w-[500px] overflow-hidden rounded-full p-4 sm:p-6">
              <div className="absolute inset-0 rounded-full bg-gradient-to-br from-white/20 via-transparent to-[#c9060a]/20" />
              <BrandLogo className="size-full border-[7px] border-white/90 shadow-[0_32px_90px_rgba(0,0,0,.45)]" priority />
            </div>
            <div className="absolute -right-2 top-8 rounded-2xl border border-white/15 bg-[#071b2c]/90 px-4 py-3 shadow-2xl backdrop-blur sm:-right-8"><span className="text-[10px] font-bold uppercase tracking-[.2em] text-[#ef9a9d]">Marca oficial</span><strong className="mt-1 block text-sm text-white">Aeromédico Brasil</strong></div>
            <div className="absolute -bottom-2 -left-4 rounded-2xl border border-white/10 bg-white p-4 text-[#071b2c] shadow-2xl sm:-left-10"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-red-50 text-[#c9060a]"><Camera className="size-5" /></span><span><strong className="block text-lg leading-none">+100 mil</strong><small className="text-slate-500">pessoas na comunidade</small></span></div></div>
          </div>
        </div>
      </section>

      <section id="atuacao" className="bg-white py-24 sm:py-28">
        <div className="page-shell"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionHeading eyebrow="Ecossistema Aeromédico Brasil" title="Preparação que conecta conhecimento e operação." /><p className="max-w-md text-sm leading-7 text-slate-500">O conteúdo parte de situações reais do universo aeromédico para organizar o aprendizado de quem está entrando na área e aprofundar a visão de quem já atua.</p></div>
          <div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{services.map((service) => { const Icon = serviceIcons[service.icon as keyof typeof serviceIcons]; return <article key={service.title} className="card-lift group relative overflow-hidden rounded-3xl border border-slate-200 bg-[#fbf9f9] p-6"><div className="flex items-start justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-[#071b2c] text-[#ef5357]"><Icon className="size-5" /></span><span className="text-xs font-bold tracking-[.2em] text-slate-300">{service.number}</span></div><h3 className="mt-8 text-lg font-bold text-[#071b2c]">{service.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{service.description}</p><ChevronRight className="mt-6 size-5 text-[#c9060a] transition-transform group-hover:translate-x-1" /></article>; })}</div>
        </div>
      </section>

      <section id="sobre" className="relative bg-[#071b2c] py-24 text-white sm:py-28">
        <div className="absolute inset-0 hero-grid opacity-40" /><div className="page-shell relative grid gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-center">
          <div className="relative min-h-[430px] overflow-hidden rounded-[2rem] border border-white/10 bg-gradient-to-br from-[#123754] to-[#03111d] p-7"><div className="absolute -right-16 -top-16 size-56 rounded-full border-[35px] border-[#c9060a]/15" /><div className="absolute bottom-0 right-0 opacity-15"><Plane className="size-64 -rotate-12" strokeWidth={.6} /></div><div className="relative flex h-full flex-col justify-between"><div className="flex items-center gap-3"><span className="h-px w-10 bg-[#c9060a]" /><span className="text-xs font-bold uppercase tracking-[.2em] text-[#ef9a9d]">Educação em saúde</span></div><div><p className="max-w-sm text-sm leading-7 text-slate-300">“Te mostro o mundo aeromédico” é o ponto de partida de uma plataforma dedicada a traduzir experiência, ciência e prática profissional.</p><div className="mt-7 flex items-center gap-4"><BrandLogo className="size-16 border-2 border-white/20" /><span><strong className="block">Lúcio Macêdo</strong><small className="text-slate-400">Aeromédico & APH · Enf. Mestre</small></span></div></div></div></div>
          <div><SectionHeading eyebrow="Quem conduz" title={about?.title ?? "Vivência de campo transformada em clareza para quem aprende."} copy={about?.body ?? "A Aeromédico Brasil reúne conteúdo técnico, orientação de carreira e educação continuada em uma experiência direta, atual e comprometida com a segurança."} light /><div className="mt-9 grid gap-4 sm:grid-cols-2">{[[BookOpen,"Conteúdo estruturado","Da base aos cenários complexos."],[Map,"Visão de carreira","Rotas para uma preparação consciente."],[Activity,"Raciocínio clínico","Decisões conectadas ao contexto."],[ShieldCheck,"Cultura de segurança","Antecipação antes, durante e após o voo."]].map(([Icon,title,copy]) => { const ItemIcon = Icon as typeof BookOpen; return <div key={title as string} className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><ItemIcon className="size-5 text-[#ef5357]" /><strong className="mt-4 block text-sm">{title as string}</strong><span className="mt-1 block text-xs leading-5 text-slate-400">{copy as string}</span></div>; })}</div></div>
        </div>
      </section>

      <section id="materiais" className="bg-[#eef4f8] py-24 sm:py-28"><div className="page-shell"><SectionHeading eyebrow="Biblioteca gratuita" title="Comece agora com materiais objetivos." copy="Escolha um conteúdo, cadastre-se e receba o acesso. Cada download entra no painel de leads para acompanhamento do projeto." /><div className="mt-12 grid gap-5 lg:grid-cols-3">{materials.map((material, index) => <article key={material.id} className="card-lift overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className={cn("relative flex h-48 flex-col justify-between overflow-hidden p-6 text-white", index === 1 ? "bg-[#0c3153]" : index === 2 ? "bg-[#14577a]" : "bg-[#07182b]")}><div className="absolute -right-8 -top-8 size-36 rounded-full border-[24px] border-white/5" /><span className="relative flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-[#8fe9ff]"><FileText className="size-4" /> {material.format}</span><h3 className="relative display-font max-w-[15rem] text-3xl font-black uppercase leading-[.95]">{material.title}</h3></div><div className="p-6"><p className="min-h-16 text-sm leading-6 text-slate-600">{material.description}</p><div className="mt-4 flex items-center gap-2 text-xs font-medium text-slate-400"><BookOpen className="size-4" /> {material.pages} páginas</div><LeadForm materialId={material.id} /></div></article>)}</div></div></section>

      <section id="cursos" className="bg-white py-24 sm:py-28"><div className="page-shell"><div className="flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><SectionHeading eyebrow="Cursos e formações" title="Escolha sua próxima evolução profissional." copy="Produtos demonstrativos preparados para integração com checkout. Valores e conteúdos podem ser editados no painel administrativo." /><span className="rounded-full bg-amber-50 px-4 py-2 text-xs font-semibold text-amber-700">Catálogo inicial editável pelo ADM</span></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{courses.map((course) => <article key={course.id} className={cn("relative flex flex-col rounded-3xl border p-6", course.featured ? "border-[#1175d1] bg-[#07182b] text-white shadow-[0_28px_70px_rgba(7,24,43,.22)]" : "border-slate-200 bg-[#f9fbfd] text-[#07182b]")}><span className={cn("self-start rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-[.16em]", course.featured ? "bg-[#38c5ea]/15 text-[#8fe9ff]" : "bg-blue-50 text-[#1175d1]")}>{course.badge}</span><h3 className="mt-7 text-2xl font-black leading-tight">{course.title}</h3><p className={cn("mt-4 min-h-20 text-sm leading-6", course.featured ? "text-slate-300" : "text-slate-600")}>{course.description}</p><div className={cn("my-6 h-px", course.featured ? "bg-white/10" : "bg-slate-200")} /><ul className="space-y-3 text-sm"><li className="flex items-center gap-3"><Clock3 className="size-4 text-[#38c5ea]" /> {course.duration}</li><li className="flex items-center gap-3"><CirclePlay className="size-4 text-[#38c5ea]" /> {course.format}</li><li className="flex items-center gap-3"><Check className="size-4 text-[#38c5ea]" /> Acesso conforme oferta</li></ul><div className="mt-8"><span className={cn("text-xs", course.featured ? "text-slate-400" : "text-slate-500")}>Investimento a partir de</span><strong className="mt-1 block text-3xl">{formatCurrency(course.price)}</strong></div><Link href={`/api/checkout?course=${course.id}`} className={cn(buttonVariants({ variant: course.featured ? "primary" : "dark", size: "lg" }), "mt-6 w-full")}>Ver oferta <ArrowRight className="size-4" /></Link></article>)}</div></div></section>

      <section className="bg-[#eef4f8] py-24 sm:py-28"><div className="page-shell"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><SectionHeading eyebrow="Confiança construída com conteúdo" title="Uma comunidade que acompanha, pergunta e evolui." copy="O projeto já reúne mais de 100 mil pessoas no Instagram. A área ao lado está pronta para receber depoimentos reais e logos autorizados diretamente pelo painel." /><Link href="https://www.instagram.com/aeromedico.brasil/" target="_blank" rel="noreferrer" className={cn(buttonVariants({ variant: "outline" }), "mt-7")}><Camera className="size-4" /> Acompanhar no Instagram</Link></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-3xl bg-[#07182b] p-7 text-white sm:row-span-2"><Users className="size-7 text-[#38c5ea]" /><strong className="display-font mt-10 block text-5xl font-black">+100K</strong><p className="mt-2 text-sm text-slate-300">pessoas acompanhando o universo aeromédico</p><div className="mt-10 flex gap-1 text-[#ff9c55]">{Array.from({ length: 5 }).map((_, i) => <Star key={i} className="size-4 fill-current" />)}</div><p className="mt-3 text-xs leading-5 text-slate-400">Avaliações serão exibidas após validação e publicação pelo administrador.</p></div>{["Depoimento de aluno", "Parceiros e instituições"].map((title) => <div key={title} className="rounded-3xl border border-dashed border-slate-300 bg-white p-6"><span className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Área gerenciável</span><h3 className="mt-5 font-bold text-[#07182b]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">Cadastre conteúdo verificado no CMS para publicar nesta seção.</p></div>)}</div></div></div></section>

      <section id="faq" className="bg-white py-24 sm:py-28"><div className="page-shell grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><SectionHeading eyebrow="Perguntas frequentes" title="Informação clara antes da decisão." copy="Ainda ficou com alguma dúvida? Fale com a equipe pelos canais oficiais." /><div className="mt-8 rounded-2xl bg-[#07182b] p-5 text-white"><Mail className="size-5 text-[#38c5ea]" /><strong className="mt-4 block">Precisa de atendimento?</strong><span className="mt-1 block text-sm text-slate-400">Configure e-mail e WhatsApp no painel do ADM.</span></div></div><Faq /></div></section>

      <section className="relative overflow-hidden bg-[#071b2c] py-20 text-white"><div className="absolute -right-20 -top-36 size-[420px] rounded-full border-[70px] border-red-600/15" /><div className="page-shell relative flex flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#ef5357]">Pronto para o próximo passo?</p><h2 className="display-font mt-3 max-w-2xl text-4xl font-black uppercase leading-none sm:text-5xl">{finalCta?.title ?? "Sua preparação não começa na aeronave."}</h2>{finalCta?.body && <p className="mt-4 max-w-xl text-sm text-slate-300">{finalCta.body}</p>}</div><Link href="#cursos" className={cn(buttonVariants({ size: "lg" }), "shrink-0")}>Conhecer formações <ArrowRight className="size-4" /></Link></div></section>

      <footer className="bg-[#03111d] py-14 text-slate-400"><div className="page-shell"><div className="grid gap-10 border-b border-white/10 pb-10 md:grid-cols-[1.4fr_1fr_1fr_1fr]"><div><div className="flex items-center gap-3 text-white"><BrandLogo className="size-12 border border-white/15" /><strong className="display-font tracking-[.08em]">AEROMÉDICO BRASIL</strong></div><p className="mt-4 max-w-sm text-sm leading-6">Conteúdo, carreira e formação para profissionais que desejam conhecer e evoluir no universo aeromédico e no APH.</p></div>{[["Navegação",[["Atuação","#atuacao"],["Materiais","#materiais"],["Cursos","#cursos"]]],["Institucional",[["Sobre","#sobre"],["FAQ","#faq"],["Área do ADM","/admin/login"]]],["Redes",[["Instagram","https://www.instagram.com/aeromedico.brasil/"],["Contato","mailto:contato@aeromedicobrasil.com.br"]]]].map(([title,links]) => <div key={title as string}><strong className="text-sm text-white">{title as string}</strong><ul className="mt-4 space-y-3 text-sm">{(links as string[][]).map(([label,href]) => <li key={label}><Link href={href} className="focus-ring rounded transition hover:text-white">{label}</Link></li>)}</ul></div>)}</div><div className="flex flex-col justify-between gap-3 pt-7 text-xs sm:flex-row"><span>© {new Date().getFullYear()} Aeromédico Brasil. Todos os direitos reservados.</span><div className="flex gap-5"><Link href="/politica-de-privacidade" className="hover:text-white">Privacidade</Link><Link href="/termos" className="hover:text-white">Termos de uso</Link></div></div></div></footer>
    </main>
  );
}
